### ISSUE TITLE
Create project structure should be updated in BBG

### ISSUE THREAD

**Issue by srsharon** [ballerina-guides/content-based-routing#20]
**Description:**
In the mentioned BBG the project structure creating sequence seems to be wrong we should init the ballerina directory before creating rest of the files.

**BBG to reproduce:**
1. [Ballerina Honeycomb](https://ballerina.io/learn/by-guide/ballerina-honeycomb/)
2. [Content Based Routing](https://github.com/ballerina-guides/content-based-routing/)

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
